# Install MongoDB

In [ ]:
%%bash
apt-get install gnupg curl
curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor
echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
apt-get update
apt-get install -y mongodb-org

Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.81.0-1ubuntu1.24).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 InRelease [3,005 B]
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://cli.github.com/packages stable/main amd64 Packages [355 B]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:9 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [100 kB]
Get:10 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 Packages [122 kB]
Get:11 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse arm64 Packages [120 kB]
Get:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,110 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:15 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.5 MB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,091 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,619 kB]
Get:19 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,332 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,615 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,313 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,426 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Fetched 41.0 MB in 5s (8,075 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  mongodb-database-tools mongodb-mongosh mongodb-org-database
  mongodb-org-database-tools-extra mongodb-org-mongos mongodb-org-server
  mongodb-org-shell mongodb-org-tools
The following NEW packages will be installed:
  mongodb-database-tools mongodb-mongosh mongodb-org mongodb-org-database
  mongodb-org-database-tools-extra mongodb-org-mongos mongodb-org-server
  mongodb-org-shell mongodb-org-tools
0 upgraded, 9 newly installed, 0 to remove and 101 not upgraded.
Need to get 189 MB of archives.
After this operation, 636 MB of additional disk space will be used.
Get:1 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-database-tools amd64 100.17.0 [60.7 MB]
Get:2 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-mongosh amd64 2.9.2 [64.3 MB]
Get:3 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-shell amd64 7.0.37 [2,990 B]
Get:4 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-server amd64 7.0.37 [37.4 MB]
Get:5 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-mongos amd64 7.0.37 [26.2 MB]
Get:6 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-database-tools-extra amd64 7.0.37 [7,784 B]
Get:7 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-database amd64 7.0.37 [3,424 B]
Get:8 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org-tools amd64 7.0.37 [2,772 B]
Get:9 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-org amd64 7.0.37 [2,804 B]
Fetched 189 MB in 2s (78.2 MB/s)
Selecting previously unselected package mongodb-database-tools.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../0-mongodb-database-tools_100.17.0_amd64.deb ...
Unpacking mongodb-database-tools (100.17.0) ...
Selecting previously unselected package mongodb-mongosh.
Preparing to unpack .../1-mongodb-mongosh_2.9.2_amd64.deb ...
Unpacking mongodb-mongosh (2.9.2) ...
Selecting previously unselected package mongodb-org-shell.
Preparing to unpack .../2-mongodb-org-shell_7.0.37_amd64.deb ...
Unpacking mongodb-org-shell (7.0.37) ...
Selecting previously unselected package mongodb-org-server.
Preparing to unpack .../3-mongodb-org-server_7.0.37_amd64.deb ...
Unpacking mongodb-org-server (7.0.37) ...
Selecting previously unselected package mongodb-org-mongos.
Preparing to unpack .../4-mongodb-org-mongos_7.0.37_amd64.deb ...
Unpacking mongodb-org-mongos (7.0.37) ...
Selecting previously unselected package mongodb-org-database-tools-extra.
Preparing to unpack .../5-mongodb-org-database-tools-extra_7.0.37_amd64.deb ...
Unpacking mongodb-org-database-tools-extra (7.0.37) ...
Selecting previously unselected package mongodb-org-database.
Preparing to unpack .../6-mongodb-org-database_7.0.37_amd64.deb ...
Unpacking mongodb-org-database (7.0.37) ...
Selecting previously unselected package mongodb-org-tools.
Preparing to unpack .../7-mongodb-org-tools_7.0.37_amd64.deb ...
Unpacking mongodb-org-tools (7.0.37) ...
Selecting previously unselected package mongodb-org.
Preparing to unpack .../8-mongodb-org_7.0.37_amd64.deb ...
Unpacking mongodb-org (7.0.37) ...
Setting up mongodb-mongosh (2.9.2) ...
Setting up mongodb-org-server (7.0.37) ...
Adding system user `mongodb' (UID 105) ...
Adding new user `mongodb' (UID 105) with group `nogroup' ...
Not creating home directory `/home/mongodb'.
Adding group `mongodb' (GID 107) ...
Done.
Adding user `mongodb' to group `mongodb' ...
Adding user mongodb to group mongodb
Done.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Setting up mongodb-org-shell (7.0.37) ...
Setting up mongodb-database-tools (100.17.0) ...
Setting up mongodb-org-mongos (7.0.37) ...
Setting up mongodb-org-database-tools-extra (7.0.37) ...
Setting up mongodb-org-database (7.0.37) ...
Setting up mongodb-org-tools (7.0.37) ...
Setting up mongodb-org (7.0.37) ...
Processing triggers for man-db (2.10.2-1) ...

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

# Check version installed

In [ ]:
!mongod --version

db version v7.0.37
Build Info: {
    "version": "7.0.37",
    "gitVersion": "9d30419d900008ba3ecf2a14546b236f2158b65b",
    "openSSLVersion": "OpenSSL 3.0.2 15 Mar 2022",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2204",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}

# Crete Data folders

In [ ]:
!mkdir /data                                          # data folder creation
!mkdir /data/db                                       # db folder creation inside data

# Start server!

In [ ]:
%%script bash --bg
mongod --dbpath /data/db

# View processes

In [ ]:
!ps fax

    PID TTY      STAT   TIME COMMAND
     43 ?        Ss     0:00 tail -n +0 -F /root/.config/Google/DriveFS/Logs/dpb
     35 ?        Ss     0:00 tail -n +0 -F /root/.config/Google/DriveFS/Logs/dri
      1 ?        Ss     0:00 /sbin/docker-init -- /datalab/run.sh
      7 ?        Sl     0:00 /tools/node/bin/node /datalab/web/app.js
     21 ?        S      0:00  \_ /bin/bash -e /usr/local/colab/bin/oom_monitor.s
   1846 ?        S      0:00  |   \_ sleep 1
     70 ?        Z      0:19  \_ [python3] <defunct>
     71 ?        S      0:03  \_ python3 /usr/local/bin/colab-fileshim.py
     92 ?        Sl     0:08  \_ /usr/bin/python3 /usr/local/bin/jupyter-server
    822 ?        Ssl    0:01  |   \_ /usr/bin/python3 -m colab_kernel_launcher -
   1858 ?        S      0:00  |       \_ bash
   1860 ?        R      0:00  |       |   \_ mongod --dbpath /data/db
   1861 ?        R      0:00  |       \_ ps fax
    845 ?        Sl     0:00  \_ /usr/colab/bin/language_service -- node /datala
    853 ?        Sl     0:06      \_ node /datalab/web/pyright/pyright-langserve
     23 ?        S      0:00 /bin/bash -e /datalab/run.sh
     24 ?        Sl     0:00  \_ /usr/colab/bin/kernel_manager_proxy --listen_po

# List databases

In [ ]:
!mongosh --eval 'db.adminCommand("listDatabases")'

]0;mongosh mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000{
  databases: [
    { name: 'admin', sizeOnDisk: Long('8192'), empty: false },
    { name: 'config', sizeOnDisk: Long('12288'), empty: false },
    { name: 'local', sizeOnDisk: Long('8192'), empty: false }
  ],
  totalSize: Long('28672'),
  totalSizeMb: Long('0'),
  ok: 1
}
]0;

In [ ]:
!mongosh --eval 'show dbs'

]0;mongosh mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000admin    8.00 KiB
config  12.00 KiB
local    8.00 KiB
]0;

# Install pymongo & pandas

In [ ]:
!pip install pymongo
!pip install pandas

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 55.0 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 20.5 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Create a connection with the mongodb collection

**EXERCICI 1**

In [ ]:
from pymongo import MongoClient
client = MongoClient()
meteo = client.meteo
weather = meteo.weather

In [ ]:
import datetime
import random
mostra = {
    "date": "2023-10-20",
    "temperature": 25.0,
    "humidity": 60.0,
    "wind_speed": 10.0,
}
weather.drop()
weather.insert_one(mostra)

dades_aleatories = []
date = datetime.datetime(2024, 1, 1)
for i in range(365):
    next_date = date + datetime.timedelta(days=i)
    registre = {
        "date": next_date.strftime("%Y-%m-%d"),
        "temperature": round(random.uniform(20.0, 30.0), 1),
        "humidity": round(random.uniform(50.0, 80.0), 1),
        "wind_speed": round(random.uniform(5.0, 15.0), 1),
    }
    dades_aleatories.append(registre)
weather.insert_many(dades_aleatories)


import pandas as pd
days = weather.find()
list_days = list(days)
df = pd.DataFrame(list_days)
df

                          _id        date  temperature  humidity  wind_speed
0    6a590af906b825f0519348f4  2023-10-20         25.0      60.0        10.0
1    6a590af906b825f0519348f5  2024-01-01         27.0      59.3        11.9
2    6a590af906b825f0519348f6  2024-01-02         20.6      73.1         9.1
3    6a590af906b825f0519348f7  2024-01-03         20.2      63.7        13.4
4    6a590af906b825f0519348f8  2024-01-04         21.1      60.5        14.6
..                        ...         ...          ...       ...         ...
361  6a590af906b825f051934a5d  2024-12-26         28.4      60.0        10.4
362  6a590af906b825f051934a5e  2024-12-27         21.2      62.7        10.1
363  6a590af906b825f051934a5f  2024-12-28         27.1      57.9         8.8
364  6a590af906b825f051934a60  2024-12-29         28.0      69.5        14.2
365  6a590af906b825f051934a61  2024-12-30         20.8      79.9        14.1

[366 rows x 5 columns]

In [ ]:
#5
days1 = weather.find({ "temperature": { "$gt": 25 } })
df1 = pd.DataFrame(list(days1))
df1

                          _id        date  temperature  humidity  wind_speed
0    6a590af906b825f0519348f5  2024-01-01         27.0      59.3        11.9
1    6a590af906b825f0519348f9  2024-01-05         27.5      55.0         6.6
2    6a590af906b825f0519348fb  2024-01-07         27.2      70.1         7.3
3    6a590af906b825f0519348fe  2024-01-10         26.2      76.3         7.0
4    6a590af906b825f051934900  2024-01-12         28.9      78.2        14.2
..                        ...         ...          ...       ...         ...
167  6a590af906b825f051934a59  2024-12-22         29.1      53.2         9.5
168  6a590af906b825f051934a5b  2024-12-24         28.0      55.2        12.5
169  6a590af906b825f051934a5d  2024-12-26         28.4      60.0        10.4
170  6a590af906b825f051934a5f  2024-12-28         27.1      57.9         8.8
171  6a590af906b825f051934a60  2024-12-29         28.0      69.5        14.2

[172 rows x 5 columns]

In [ ]:
days2 = weather.find({ "wind_speed": { "$gt": 10 } })
df2 = pd.DataFrame(list(days2))
df2

                          _id        date  temperature  humidity  wind_speed
0    6a590af906b825f0519348f5  2024-01-01         27.0      59.3        11.9
1    6a590af906b825f0519348f7  2024-01-03         20.2      63.7        13.4
2    6a590af906b825f0519348f8  2024-01-04         21.1      60.5        14.6
3    6a590af906b825f0519348fa  2024-01-06         23.1      59.9        12.3
4    6a590af906b825f0519348fc  2024-01-08         24.7      70.7        13.2
..                        ...         ...          ...       ...         ...
179  6a590af906b825f051934a5c  2024-12-25         24.8      54.7        10.5
180  6a590af906b825f051934a5d  2024-12-26         28.4      60.0        10.4
181  6a590af906b825f051934a5e  2024-12-27         21.2      62.7        10.1
182  6a590af906b825f051934a60  2024-12-29         28.0      69.5        14.2
183  6a590af906b825f051934a61  2024-12-30         20.8      79.9        14.1

[184 rows x 5 columns]

In [ ]:
days3 = weather.find({ "humidity": { "$lt": 70 } })
df3 = pd.DataFrame(list(days3))
df3

                          _id        date  temperature  humidity  wind_speed
0    6a590af906b825f0519348f4  2023-10-20         25.0      60.0        10.0
1    6a590af906b825f0519348f5  2024-01-01         27.0      59.3        11.9
2    6a590af906b825f0519348f7  2024-01-03         20.2      63.7        13.4
3    6a590af906b825f0519348f8  2024-01-04         21.1      60.5        14.6
4    6a590af906b825f0519348f9  2024-01-05         27.5      55.0         6.6
..                        ...         ...          ...       ...         ...
224  6a590af906b825f051934a5c  2024-12-25         24.8      54.7        10.5
225  6a590af906b825f051934a5d  2024-12-26         28.4      60.0        10.4
226  6a590af906b825f051934a5e  2024-12-27         21.2      62.7        10.1
227  6a590af906b825f051934a5f  2024-12-28         27.1      57.9         8.8
228  6a590af906b825f051934a60  2024-12-29         28.0      69.5        14.2

[229 rows x 5 columns]

In [ ]:
days4 = weather.find({ "temperature": { "$gt": 20 }, "temperature": { "$lt": 25 }})
df4 = pd.DataFrame(list(days4))
df4

                          _id        date  temperature  humidity  wind_speed
0    6a590af906b825f0519348f6  2024-01-02         20.6      73.1         9.1
1    6a590af906b825f0519348f7  2024-01-03         20.2      63.7        13.4
2    6a590af906b825f0519348f8  2024-01-04         21.1      60.5        14.6
3    6a590af906b825f0519348fa  2024-01-06         23.1      59.9        12.3
4    6a590af906b825f0519348fc  2024-01-08         24.7      70.7        13.2
..                        ...         ...          ...       ...         ...
187  6a590af906b825f051934a56  2024-12-19         20.0      77.6         8.4
188  6a590af906b825f051934a5a  2024-12-23         21.7      54.6         6.3
189  6a590af906b825f051934a5c  2024-12-25         24.8      54.7        10.5
190  6a590af906b825f051934a5e  2024-12-27         21.2      62.7        10.1
191  6a590af906b825f051934a61  2024-12-30         20.8      79.9        14.1

[192 rows x 5 columns]

In [ ]:
days5 = weather.find({ "wind_speed": { "$gt": 10 }, "humidity": { "$lt": 60 }})
df5 = pd.DataFrame(list(days5))
df5

                         _id        date  temperature  humidity  wind_speed
0   6a590af906b825f0519348f5  2024-01-01         27.0      59.3        11.9
1   6a590af906b825f0519348fa  2024-01-06         23.1      59.9        12.3
2   6a590af906b825f05193490b  2024-01-23         22.8      52.7        11.2
3   6a590af906b825f051934910  2024-01-28         24.1      55.4        11.5
4   6a590af906b825f051934913  2024-01-31         26.4      56.2        13.7
..                       ...         ...          ...       ...         ...
62  6a590af906b825f051934a46  2024-12-03         27.5      57.1        13.4
63  6a590af906b825f051934a54  2024-12-17         29.6      55.7        12.7
64  6a590af906b825f051934a58  2024-12-21         27.9      59.4        13.3
65  6a590af906b825f051934a5b  2024-12-24         28.0      55.2        12.5
66  6a590af906b825f051934a5c  2024-12-25         24.8      54.7        10.5

[67 rows x 5 columns]

In [ ]:
#10
import json

def prepare_df_for_json(df_input):
    df_copy = df_input.copy()
    if '_id' in df_copy.columns:
        df_copy['_id'] = df_copy['_id'].astype(str)
    return df_copy.to_dict(orient='records')

all_results = {
    "days1_temp_gt_25": prepare_df_for_json(df1),
    "days2_wind_gt_10": prepare_df_for_json(df2),
    "days3_humidity_lt_70": prepare_df_for_json(df3),
    "days4_temp_20_to_25": prepare_df_for_json(df4),
    "days5_wind_gt_10_humidity_lt_60": prepare_df_for_json(df5)
}

# Write results to a JSON file
with open('weather_results.json', 'w') as f:
    json.dump(all_results, f, indent=4)

In [ ]:
#11
import random

for doc in weather.find():
    random_rain = round(random.uniform(0.0, 10.0), 1)
    weather.update_one(
        {"_id": doc["_id"]},
        {"$set": {"rain": random_rain}}
    )
df = pd.DataFrame(list(weather.find()))
df

,_id,date,temperature,humidity,wind_speed,rain
0,6a590af906b825f0519348f4,2023-10-20,25.0,60.0,10.0,9.7
1,6a590af906b825f0519348f5,2024-01-01,27.0,59.3,11.9,7.0
2,6a590af906b825f0519348f6,2024-01-02,20.6,73.1,9.1,9.6
3,6a590af906b825f0519348f7,2024-01-03,20.2,63.7,13.4,7.6
4,6a590af906b825f0519348f8,2024-01-04,21.1,60.5,14.6,9.8
...,...,...,...,...,...,...
361,6a590af906b825f051934a5d,2024-12-26,28.4,60.0,10.4,6.6
362,6a590af906b825f051934a5e,2024-12-27,21.2,62.7,10.1,7.4
363,6a590af906b825f051934a5f,2024-12-28,27.1,57.9,8.8,6.5
364,6a590af906b825f051934a60,2024-12-29,28.0,69.5,14.2,6.9
365,6a590af906b825f051934a61,2024-12-30,20.8,79.9,14.1,0.8

In [ ]:
# 12
result = weather.delete_many({"date": {"$gte": "2024-05-01","$lt": "2024-06-01"}})

dfx = pd.DataFrame(list(weather.find()))
dfx

,_id,date,temperature,humidity,wind_speed,rain
0,6a590af906b825f0519348f4,2023-10-20,25.0,60.0,10.0,9.7
1,6a590af906b825f0519348f5,2024-01-01,27.0,59.3,11.9,7.0
2,6a590af906b825f0519348f6,2024-01-02,20.6,73.1,9.1,9.6
3,6a590af906b825f0519348f7,2024-01-03,20.2,63.7,13.4,7.6
4,6a590af906b825f0519348f8,2024-01-04,21.1,60.5,14.6,9.8
...,...,...,...,...,...,...
330,6a590af906b825f051934a5d,2024-12-26,28.4,60.0,10.4,6.6
331,6a590af906b825f051934a5e,2024-12-27,21.2,62.7,10.1,7.4
332,6a590af906b825f051934a5f,2024-12-28,27.1,57.9,8.8,6.5
333,6a590af906b825f051934a60,2024-12-29,28.0,69.5,14.2,6.9
334,6a590af906b825f051934a61,2024-12-30,20.8,79.9,14.1,0.8

**EXERCICI 2**

In [ ]:
from pymongo import MongoClient
client = MongoClient()
cattle = client.cattle

In [ ]:
import json
import pandas as pd

df_ganado = pd.read_json('/content/sample_data/censo-ganado.json')

census = cattle.census

cattle.ganado.insert_many(df_ganado.to_dict('records'))

InsertManyResult([ObjectId('6a59134306b825f05193e82d'), ObjectId('6a59134306b825f05193e82e'), ObjectId('6a59134306b825f05193e82f'), ObjectId('6a59134306b825f05193e830'), ObjectId('6a59134306b825f05193e831'), ObjectId('6a59134306b825f05193e832'), ObjectId('6a59134306b825f05193e833'), ObjectId('6a59134306b825f05193e834'), ObjectId('6a59134306b825f05193e835'), ObjectId('6a59134306b825f05193e836'), ObjectId('6a59134306b825f05193e837'), ObjectId('6a59134306b825f05193e838'), ObjectId('6a59134306b825f05193e839'), ObjectId('6a59134306b825f05193e83a'), ObjectId('6a59134306b825f05193e83b'), ObjectId('6a59134306b825f05193e83c'), ObjectId('6a59134306b825f05193e83d'), ObjectId('6a59134306b825f05193e83e'), ObjectId('6a59134306b825f05193e83f'), ObjectId('6a59134306b825f05193e840'), ObjectId('6a59134306b825f05193e841'), ObjectId('6a59134306b825f05193e842'), ObjectId('6a59134306b825f05193e843'), ObjectId('6a59134306b825f05193e844'), ObjectId('6a59134306b825f05193e845'), ObjectId('6a59134306b825f05193e846'), ObjectId('6a59134306b825f05193e847'), ObjectId('6a59134306b825f05193e848'), ObjectId('6a59134306b825f05193e849'), ObjectId('6a59134306b825f05193e84a'), ObjectId('6a59134306b825f05193e84b'), ObjectId('6a59134306b825f05193e84c'), ObjectId('6a59134306b825f05193e84d'), ObjectId('6a59134306b825f05193e84e'), ObjectId('6a59134306b825f05193e84f'), ObjectId('6a59134306b825f05193e850'), ObjectId('6a59134306b825f05193e851'), ObjectId('6a59134306b825f05193e852'), ObjectId('6a59134306b825f05193e853'), ObjectId('6a59134306b825f05193e854'), ObjectId('6a59134306b825f05193e855'), ObjectId('6a59134306b825f05193e856'), ObjectId('6a59134306b825f05193e857'), ObjectId('6a59134306b825f05193e858'), ObjectId('6a59134306b825f05193e859'), ObjectId('6a59134306b825f05193e85a'), ObjectId('6a59134306b825f05193e85b'), ObjectId('6a59134306b825f05193e85c'), ObjectId('6a59134306b825f05193e85d'), ObjectId('6a59134306b825f05193e85e'), ObjectId('6a59134306b825f05193e85f'), ObjectId('6a59134306b825f05193e860'), ObjectId('6a59134306b825f05193e861'), ObjectId('6a59134306b825f05193e862'), ObjectId('6a59134306b825f05193e863'), ObjectId('6a59134306b825f05193e864'), ObjectId('6a59134306b825f05193e865'), ObjectId('6a59134306b825f05193e866'), ObjectId('6a59134306b825f05193e867'), ObjectId('6a59134306b825f05193e868'), ObjectId('6a59134306b825f05193e869'), ObjectId('6a59134306b825f05193e86a'), ObjectId('6a59134306b825f05193e86b'), ObjectId('6a59134306b825f05193e86c'), ObjectId('6a59134306b825f05193e86d'), ObjectId('6a59134306b825f05193e86e'), ObjectId('6a59134306b825f05193e86f'), ObjectId('6a59134306b825f05193e870'), ObjectId('6a59134306b825f05193e871'), ObjectId('6a59134306b825f05193e872'), ObjectId('6a59134306b825f05193e873'), ObjectId('6a59134306b825f05193e874'), ObjectId('6a59134306b825f05193e875'), ObjectId('6a59134306b825f05193e876'), ObjectId('6a59134306b825f05193e877'), ObjectId('6a59134306b825f05193e878'), ObjectId('6a59134306b825f05193e879'), ObjectId('6a59134306b825f05193e87a'), ObjectId('6a59134306b825f05193e87b'), ObjectId('6a59134306b825f05193e87c'), ObjectId('6a59134306b825f05193e87d'), ObjectId('6a59134306b825f05193e87e'), ObjectId('6a59134306b825f05193e87f'), ObjectId('6a59134306b825f05193e880'), ObjectId('6a59134306b825f05193e881'), ObjectId('6a59134306b825f05193e882'), ObjectId('6a59134306b825f05193e883'), ObjectId('6a59134306b825f05193e884'), ObjectId('6a59134306b825f05193e885'), ObjectId('6a59134306b825f05193e886'), ObjectId('6a59134306b825f05193e887'), ObjectId('6a59134306b825f05193e888'), ObjectId('6a59134306b825f05193e889'), ObjectId('6a59134306b825f05193e88a'), ObjectId('6a59134306b825f05193e88b'), ObjectId('6a59134306b825f05193e88c'), ObjectId('6a59134306b825f05193e88d'), ObjectId('6a59134306b825f05193e88e'), ObjectId('6a59134306b825f05193e88f'), ObjectId('6a59134306b825f05193e890'), ObjectId('6a59134306b825f05193e891'), ObjectId('6a59134306b825f05193e892'), ObjectId('6a59134306b825f05193e893'), ObjectId('6a59134306b825f05193e894'), ObjectId('6a59134306b825f05193e895'), ObjectId('6a59134306b825f05193e896'), ObjectId('6a59134306b825f05193e897'), ObjectId('6a59134306b825f05193e898'), ObjectId('6a59134306b825f05193e899'), ObjectId('6a59134306b825f05193e89a'), ObjectId('6a59134306b825f05193e89b'), ObjectId('6a59134306b825f05193e89c'), ObjectId('6a59134306b825f05193e89d'), ObjectId('6a59134306b825f05193e89e'), ObjectId('6a59134306b825f05193e89f'), ObjectId('6a59134306b825f05193e8a0'), ObjectId('6a59134306b825f05193e8a1'), ObjectId('6a59134306b825f05193e8a2'), ObjectId('6a59134306b825f05193e8a3'), ObjectId('6a59134306b825f05193e8a4'), ObjectId('6a59134306b825f05193e8a5'), ObjectId('6a59134306b825f05193e8a6'), ObjectId('6a59134306b825f05193e8a7'), ObjectId('6a59134306b825f05193e8a8'), ObjectId('6a59134306b825f05193e8a9'), ObjectId('6a59134306b825f05193e8aa'), ObjectId('6a59134306b825f05193e8ab'), ObjectId('6a59134306b825f05193e8ac'), ObjectId('6a59134306b825f05193e8ad'), ObjectId('6a59134306b825f05193e8ae'), ObjectId('6a59134306b825f05193e8af'), ObjectId('6a59134306b825f05193e8b0'), ObjectId('6a59134306b825f05193e8b1'), ObjectId('6a59134306b825f05193e8b2'), ObjectId('6a59134306b825f05193e8b3'), ObjectId('6a59134306b825f05193e8b4'), ObjectId('6a59134306b825f05193e8b5'), ObjectId('6a59134306b825f05193e8b6'), ObjectId('6a59134306b825f05193e8b7'), ObjectId('6a59134306b825f05193e8b8'), ObjectId('6a59134306b825f05193e8b9'), ObjectId('6a59134306b825f05193e8ba'), ObjectId('6a59134306b825f05193e8bb'), ObjectId('6a59134306b825f05193e8bc'), ObjectId('6a59134306b825f05193e8bd'), ObjectId('6a59134306b825f05193e8be'), ObjectId('6a59134306b825f05193e8bf'), ObjectId('6a59134306b825f05193e8c0'), ObjectId('6a59134306b825f05193e8c1'), ObjectId('6a59134306b825f05193e8c2'), ObjectId('6a59134306b825f05193e8c3'), ObjectId('6a59134306b825f05193e8c4'), ObjectId('6a59134306b825f05193e8c5'), ObjectId('6a59134306b825f05193e8c6'), ObjectId('6a59134306b825f05193e8c7'), ObjectId('6a59134306b825f05193e8c8'), ObjectId('6a59134306b825f05193e8c9'), ObjectId('6a59134306b825f05193e8ca'), ObjectId('6a59134306b825f05193e8cb'), ObjectId('6a59134306b825f05193e8cc'), ObjectId('6a59134306b825f05193e8cd'), ObjectId('6a59134306b825f05193e8ce'), ObjectId('6a59134306b825f05193e8cf'), ObjectId('6a59134306b825f05193e8d0'), ObjectId('6a59134306b825f05193e8d1'), ObjectId('6a59134306b825f05193e8d2'), ObjectId('6a59134306b825f05193e8d3'), ObjectId('6a59134306b825f05193e8d4'), ObjectId('6a59134306b825f05193e8d5'), ObjectId('6a59134306b825f05193e8d6'), ObjectId('6a59134306b825f05193e8d7'), ObjectId('6a59134306b825f05193e8d8'), ObjectId('6a59134306b825f05193e8d9'), ObjectId('6a59134306b825f05193e8da'), ObjectId('6a59134306b825f05193e8db'), ObjectId('6a59134306b825f05193e8dc'), ObjectId('6a59134306b825f05193e8dd'), ObjectId('6a59134306b825f05193e8de'), ObjectId('6a59134306b825f05193e8df'), ObjectId('6a59134306b825f05193e8e0'), ObjectId('6a59134306b825f05193e8e1'), ObjectId('6a59134306b825f05193e8e2'), ObjectId('6a59134306b825f05193e8e3'), ObjectId('6a59134306b825f05193e8e4'), ObjectId('6a59134306b825f05193e8e5'), ObjectId('6a59134306b825f05193e8e6'), ObjectId('6a59134306b825f05193e8e7'), ObjectId('6a59134306b825f05193e8e8'), ObjectId('6a59134306b825f05193e8e9'), ObjectId('6a59134306b825f05193e8ea'), ObjectId('6a59134306b825f05193e8eb'), ObjectId('6a59134306b825f05193e8ec'), ObjectId('6a59134306b825f05193e8ed'), ObjectId('6a59134306b825f05193e8ee'), ObjectId('6a59134306b825f05193e8ef'), ObjectId('6a59134306b825f05193e8f0'), ObjectId('6a59134306b825f05193e8f1'), ObjectId('6a59134306b825f05193e8f2'), ObjectId('6a59134306b825f05193e8f3'), ObjectId('6a59134306b825f05193e8f4'), ObjectId('6a59134306b825f05193e8f5'), ObjectId('6a59134306b825f05193e8f6'), ObjectId('6a59134306b825f05193e8f7'), ObjectId('6a59134306b825f05193e8f8'), ObjectId('6a59134306b825f05193e8f9'), ObjectId('6a59134306b825f05193e8fa'), ObjectId('6a59134306b825f05193e8fb'), ObjectId('6a59134306b825f05193e8fc'), ObjectId('6a59134306b825f05193e8fd'), ObjectId('6a59134306b825f05193e8fe'), ObjectId('6a59134306b825f05193e8ff'), ObjectId('6a59134306b825f05193e900'), ObjectId('6a59134306b825f05193e901'), ObjectId('6a59134306b825f05193e902'), ObjectId('6a59134306b825f05193e903'), ObjectId('6a59134306b825f05193e904'), ObjectId('6a59134306b825f05193e905'), ObjectId('6a59134306b825f05193e906'), ObjectId('6a59134306b825f05193e907'), ObjectId('6a59134306b825f05193e908'), ObjectId('6a59134306b825f05193e909'), ObjectId('6a59134306b825f05193e90a'), ObjectId('6a59134306b825f05193e90b'), ObjectId('6a59134306b825f05193e90c'), ObjectId('6a59134306b825f05193e90d'), ObjectId('6a59134306b825f05193e90e'), ObjectId('6a59134306b825f05193e90f'), ObjectId('6a59134306b825f05193e910'), ObjectId('6a59134306b825f05193e911'), ObjectId('6a59134306b825f05193e912'), ObjectId('6a59134306b825f05193e913'), ObjectId('6a59134306b825f05193e914'), ObjectId('6a59134306b825f05193e915'), ObjectId('6a59134306b825f05193e916'), ObjectId('6a59134306b825f05193e917'), ObjectId('6a59134306b825f05193e918'), ObjectId('6a59134306b825f05193e919'), ObjectId('6a59134306b825f05193e91a'), ObjectId('6a59134306b825f05193e91b'), ObjectId('6a59134306b825f05193e91c'), ObjectId('6a59134306b825f05193e91d'), ObjectId('6a59134306b825f05193e91e'), ObjectId('6a59134306b825f05193e91f'), ObjectId('6a59134306b825f05193e920'), ObjectId('6a59134306b825f05193e921'), ObjectId('6a59134306b825f05193e922'), ObjectId('6a59134306b825f05193e923'), ObjectId('6a59134306b825f05193e924'), ObjectId('6a59134306b825f05193e925'), ObjectId('6a59134306b825f05193e926'), ObjectId('6a59134306b825f05193e927'), ObjectId('6a59134306b825f05193e928'), ObjectId('6a59134306b825f05193e929'), ObjectId('6a59134306b825f05193e92a'), ObjectId('6a59134306b825f05193e92b'), ObjectId('6a59134306b825f05193e92c'), ObjectId('6a59134306b825f05193e92d'), ObjectId('6a59134306b825f05193e92e'), ObjectId('6a59134306b825f05193e92f'), ObjectId('6a59134306b825f05193e930'), ObjectId('6a59134306b825f05193e931'), ObjectId('6a59134306b825f05193e932'), ObjectId('6a59134306b825f05193e933'), ObjectId('6a59134306b825f05193e934'), ObjectId('6a59134306b825f05193e935'), ObjectId('6a59134306b825f05193e936'), ObjectId('6a59134306b825f05193e937'), ObjectId('6a59134306b825f05193e938'), ObjectId('6a59134306b825f05193e939'), ObjectId('6a59134306b825f05193e93a'), ObjectId('6a59134306b825f05193e93b'), ObjectId('6a59134306b825f05193e93c'), ObjectId('6a59134306b825f05193e93d'), ObjectId('6a59134306b825f05193e93e'), ObjectId('6a59134306b825f05193e93f'), ObjectId('6a59134306b825f05193e940'), ObjectId('6a59134306b825f05193e941'), ObjectId('6a59134306b825f05193e942'), ObjectId('6a59134306b825f05193e943'), ObjectId('6a59134306b825f05193e944'), ObjectId('6a59134306b825f05193e945'), ObjectId('6a59134306b825f05193e946'), ObjectId('6a59134306b825f05193e947'), ObjectId('6a59134306b825f05193e948'), ObjectId('6a59134306b825f05193e949'), ObjectId('6a59134306b825f05193e94a'), ObjectId('6a59134306b825f05193e94b'), ObjectId('6a59134306b825f05193e94c'), ObjectId('6a59134306b825f05193e94d'), ObjectId('6a59134306b825f05193e94e'), ObjectId('6a59134306b825f05193e94f'), ObjectId('6a59134306b825f05193e950'), ObjectId('6a59134306b825f05193e951'), ObjectId('6a59134306b825f05193e952'), ObjectId('6a59134306b825f05193e953'), ObjectId('6a59134306b825f05193e954'), ObjectId('6a59134306b825f05193e955'), ObjectId('6a59134306b825f05193e956'), ObjectId('6a59134306b825f05193e957'), ObjectId('6a59134306b825f05193e958'), ObjectId('6a59134306b825f05193e959'), ObjectId('6a59134306b825f05193e95a'), ObjectId('6a59134306b825f05193e95b'), ObjectId('6a59134306b825f05193e95c'), ObjectId('6a59134306b825f05193e95d'), ObjectId('6a59134306b825f05193e95e'), ObjectId('6a59134306b825f05193e95f'), ObjectId('6a59134306b825f05193e960'), ObjectId('6a59134306b825f05193e961'), ObjectId('6a59134306b825f05193e962'), ObjectId('6a59134306b825f05193e963'), ObjectId('6a59134306b825f05193e964'), ObjectId('6a59134306b825f05193e965'), ObjectId('6a59134306b825f05193e966'), ObjectId('6a59134306b825f05193e967'), ObjectId('6a59134306b825f05193e968'), ObjectId('6a59134306b825f05193e969'), ObjectId('6a59134306b825f05193e96a'), ObjectId('6a59134306b825f05193e96b'), ObjectId('6a59134306b825f05193e96c'), ObjectId('6a59134306b825f05193e96d'), ObjectId('6a59134306b825f05193e96e'), ObjectId('6a59134306b825f05193e96f'), ObjectId('6a59134306b825f05193e970'), ObjectId('6a59134306b825f05193e971'), ObjectId('6a59134306b825f05193e972'), ObjectId('6a59134306b825f05193e973'), ObjectId('6a59134306b825f05193e974'), ObjectId('6a59134306b825f05193e975'), ObjectId('6a59134306b825f05193e976'), ObjectId('6a59134306b825f05193e977'), ObjectId('6a59134306b825f05193e978'), ObjectId('6a59134306b825f05193e979'), ObjectId('6a59134306b825f05193e97a'), ObjectId('6a59134306b825f05193e97b'), ObjectId('6a59134306b825f05193e97c'), ObjectId('6a59134306b825f05193e97d'), ObjectId('6a59134306b825f05193e97e'), ObjectId('6a59134306b825f05193e97f'), ObjectId('6a59134306b825f05193e980'), ObjectId('6a59134306b825f05193e981'), ObjectId('6a59134306b825f05193e982'), ObjectId('6a59134306b825f05193e983'), ObjectId('6a59134306b825f05193e984'), ObjectId('6a59134306b825f05193e985'), ObjectId('6a59134306b825f05193e986'), ObjectId('6a59134306b825f05193e987'), ObjectId('6a59134306b825f05193e988'), ObjectId('6a59134306b825f05193e989'), ObjectId('6a59134306b825f05193e98a'), ObjectId('6a59134306b825f05193e98b'), ObjectId('6a59134306b825f05193e98c'), ObjectId('6a59134306b825f05193e98d'), ObjectId('6a59134306b825f05193e98e'), ObjectId('6a59134306b825f05193e98f'), ObjectId('6a59134306b825f05193e990'), ObjectId('6a59134306b825f05193e991'), ObjectId('6a59134306b825f05193e992'), ObjectId('6a59134306b825f05193e993'), ObjectId('6a59134306b825f05193e994'), ObjectId('6a59134306b825f05193e995'), ObjectId('6a59134306b825f05193e996'), ObjectId('6a59134306b825f05193e997'), ObjectId('6a59134306b825f05193e998'), ObjectId('6a59134306b825f05193e999'), ObjectId('6a59134306b825f05193e99a'), ObjectId('6a59134306b825f05193e99b'), ObjectId('6a59134306b825f05193e99c'), ObjectId('6a59134306b825f05193e99d'), ObjectId('6a59134306b825f05193e99e'), ObjectId('6a59134306b825f05193e99f'), ObjectId('6a59134306b825f05193e9a0'), ObjectId('6a59134306b825f05193e9a1'), ObjectId('6a59134306b825f05193e9a2'), ObjectId('6a59134306b825f05193e9a3'), ObjectId('6a59134306b825f05193e9a4'), ObjectId('6a59134306b825f05193e9a5'), ObjectId('6a59134306b825f05193e9a6'), ObjectId('6a59134306b825f05193e9a7'), ObjectId('6a59134306b825f05193e9a8'), ObjectId('6a59134306b825f05193e9a9'), ObjectId('6a59134306b825f05193e9aa'), ObjectId('6a59134306b825f05193e9ab'), ObjectId('6a59134306b825f05193e9ac'), ObjectId('6a59134306b825f05193e9ad'), ObjectId('6a59134306b825f05193e9ae'), ObjectId('6a59134306b825f05193e9af'), ObjectId('6a59134306b825f05193e9b0'), ObjectId('6a59134306b825f05193e9b1'), ObjectId('6a59134306b825f05193e9b2'), ObjectId('6a59134306b825f05193e9b3'), ObjectId('6a59134306b825f05193e9b4'), ObjectId('6a59134306b825f05193e9b5'), ObjectId('6a59134306b825f05193e9b6'), ObjectId('6a59134306b825f05193e9b7'), ObjectId('6a59134306b825f05193e9b8'), ObjectId('6a59134306b825f05193e9b9'), ObjectId('6a59134306b825f05193e9ba'), ObjectId('6a59134306b825f05193e9bb'), ObjectId('6a59134306b825f05193e9bc'), ObjectId('6a59134306b825f05193e9bd'), ObjectId('6a59134306b825f05193e9be'), ObjectId('6a59134306b825f05193e9bf'), ObjectId('6a59134306b825f05193e9c0'), ObjectId('6a59134306b825f05193e9c1'), ObjectId('6a59134306b825f05193e9c2'), ObjectId('6a59134306b825f05193e9c3'), ObjectId('6a59134306b825f05193e9c4'), ObjectId('6a59134306b825f05193e9c5'), ObjectId('6a59134306b825f05193e9c6'), ObjectId('6a59134306b825f05193e9c7'), ObjectId('6a59134306b825f05193e9c8'), ObjectId('6a59134306b825f05193e9c9'), ObjectId('6a59134306b825f05193e9ca'), ObjectId('6a59134306b825f05193e9cb'), ObjectId('6a59134306b825f05193e9cc'), ObjectId('6a59134306b825f05193e9cd'), ObjectId('6a59134306b825f05193e9ce'), ObjectId('6a59134306b825f05193e9cf'), ObjectId('6a59134306b825f05193e9d0'), ObjectId('6a59134306b825f05193e9d1'), ObjectId('6a59134306b825f05193e9d2'), ObjectId('6a59134306b825f05193e9d3'), ObjectId('6a59134306b825f05193e9d4'), ObjectId('6a59134306b825f05193e9d5'), ObjectId('6a59134306b825f05193e9d6'), ObjectId('6a59134306b825f05193e9d7'), ObjectId('6a59134306b825f05193e9d8'), ObjectId('6a59134306b825f05193e9d9'), ObjectId('6a59134306b825f05193e9da'), ObjectId('6a59134306b825f05193e9db'), ObjectId('6a59134306b825f05193e9dc'), ObjectId('6a59134306b825f05193e9dd'), ObjectId('6a59134306b825f05193e9de'), ObjectId('6a59134306b825f05193e9df'), ObjectId('6a59134306b825f05193e9e0'), ObjectId('6a59134306b825f05193e9e1'), ObjectId('6a59134306b825f05193e9e2'), ObjectId('6a59134306b825f05193e9e3'), ObjectId('6a59134306b825f05193e9e4'), ObjectId('6a59134306b825f05193e9e5'), ObjectId('6a59134306b825f05193e9e6'), ObjectId('6a59134306b825f05193e9e7'), ObjectId('6a59134306b825f05193e9e8'), ObjectId('6a59134306b825f05193e9e9'), ObjectId('6a59134306b825f05193e9ea'), ObjectId('6a59134306b825f05193e9eb'), ObjectId('6a59134306b825f05193e9ec'), ObjectId('6a59134306b825f05193e9ed'), ObjectId('6a59134306b825f05193e9ee'), ObjectId('6a59134306b825f05193e9ef'), ObjectId('6a59134306b825f05193e9f0'), ObjectId('6a59134306b825f05193e9f1'), ObjectId('6a59134306b825f05193e9f2'), ObjectId('6a59134306b825f05193e9f3'), ObjectId('6a59134306b825f05193e9f4'), ObjectId('6a59134306b825f05193e9f5'), ObjectId('6a59134306b825f05193e9f6'), ObjectId('6a59134306b825f05193e9f7'), ObjectId('6a59134306b825f05193e9f8'), ObjectId('6a59134306b825f05193e9f9'), ObjectId('6a59134306b825f05193e9fa'), ObjectId('6a59134306b825f05193e9fb'), ObjectId('6a59134306b825f05193e9fc'), ObjectId('6a59134306b825f05193e9fd'), ObjectId('6a59134306b825f05193e9fe'), ObjectId('6a59134306b825f05193e9ff'), ObjectId('6a59134306b825f05193ea00'), ObjectId('6a59134306b825f05193ea01'), ObjectId('6a59134306b825f05193ea02'), ObjectId('6a59134306b825f05193ea03'), ObjectId('6a59134306b825f05193ea04'), ObjectId('6a59134306b825f05193ea05'), ObjectId('6a59134306b825f05193ea06'), ObjectId('6a59134306b825f05193ea07'), ObjectId('6a59134306b825f05193ea08'), ObjectId('6a59134306b825f05193ea09'), ObjectId('6a59134306b825f05193ea0a'), ObjectId('6a59134306b825f05193ea0b'), ObjectId('6a59134306b825f05193ea0c'), ObjectId('6a59134306b825f05193ea0d'), ObjectId('6a59134306b825f05193ea0e'), ObjectId('6a59134306b825f05193ea0f'), ObjectId('6a59134306b825f05193ea10'), ObjectId('6a59134306b825f05193ea11'), ObjectId('6a59134306b825f05193ea12'), ObjectId('6a59134306b825f05193ea13'), ObjectId('6a59134306b825f05193ea14'), ObjectId('6a59134306b825f05193ea15'), ObjectId('6a59134306b825f05193ea16'), ObjectId('6a59134306b825f05193ea17'), ObjectId('6a59134306b825f05193ea18'), ObjectId('6a59134306b825f05193ea19'), ObjectId('6a59134306b825f05193ea1a'), ObjectId('6a59134306b825f05193ea1b'), ObjectId('6a59134306b825f05193ea1c'), ObjectId('6a59134306b825f05193ea1d'), ObjectId('6a59134306b825f05193ea1e'), ObjectId('6a59134306b825f05193ea1f'), ObjectId('6a59134306b825f05193ea20'), ObjectId('6a59134306b825f05193ea21'), ObjectId('6a59134306b825f05193ea22'), ObjectId('6a59134306b825f05193ea23'), ObjectId('6a59134306b825f05193ea24'), ObjectId('6a59134306b825f05193ea25'), ObjectId('6a59134306b825f05193ea26'), ObjectId('6a59134306b825f05193ea27'), ObjectId('6a59134306b825f05193ea28'), ObjectId('6a59134306b825f05193ea29'), ObjectId('6a59134306b825f05193ea2a'), ObjectId('6a59134306b825f05193ea2b'), ObjectId('6a59134306b825f05193ea2c'), ObjectId('6a59134306b825f05193ea2d'), ObjectId('6a59134306b825f05193ea2e'), ObjectId('6a59134306b825f05193ea2f'), ObjectId('6a59134306b825f05193ea30'), ObjectId('6a59134306b825f05193ea31'), ObjectId('6a59134306b825f05193ea32'), ObjectId('6a59134306b825f05193ea33'), ObjectId('6a59134306b825f05193ea34'), ObjectId('6a59134306b825f05193ea35'), ObjectId('6a59134306b825f05193ea36'), ObjectId('6a59134306b825f05193ea37'), ObjectId('6a59134306b825f05193ea38'), ObjectId('6a59134306b825f05193ea39'), ObjectId('6a59134306b825f05193ea

In [ ]:
# 3
cattle_gt_1000 = cattle.ganado.find({"Número de reses": {"$gt": 1000}})

df_cattle_gt_1000 = pd.DataFrame(list(cattle_gt_1000))

df_cattle_gt_1000

,_id,Año,Especie,Municipio,Número de explotaciones,Número de reses,Reses por explotación
0,6a59134306b825f05193e82d,2001,Vacuno,39001 - Alfoz de Lloredo,170.0,3829.0,22.52
1,6a59134306b825f05193e82e,2001,Vacuno,39002 - Ampuero,128.0,3251.0,25.40
2,6a59134306b825f05193e82f,2001,Vacuno,39003 - Anievas,59.0,1405.0,23.81
3,6a59134306b825f05193e830,2001,Vacuno,39004 - Arenas de Iguña,194.0,3925.0,20.23
4,6a59134306b825f05193e832,2001,Vacuno,39006 - Arnuero,109.0,3546.0,32.53
...,...,...,...,...,...,...,...
6172,6a59134406b825f0519436be,2022,Caprino,39020 - Castro-Urdiales,82.0,2117.0,25.82
6173,6a59134406b825f0519436c8,2022,Caprino,39030 - Guriezo,67.0,1387.0,20.70
6174,6a59134406b825f0519436cf,2022,Caprino,39037 - Liérganes,66.0,1009.0,15.29
6175,6a59134406b825f0519436ed,2022,Caprino,39067 - Ruesga,50.0,1119.0,22.38
6176,6a59134406b825f0519436fd,2022,Caprino,39083 - Soba,70.0,1240.0,17.71

In [ ]:
#4
cattle_filtered = cattle.ganado.find({
    "Número de reses": {"$gt": 100},
    "Número de explotaciones": {"$gt": 10}
})

df_cattle_filtered = pd.DataFrame(list(cattle_filtered))

df_cattle_filtered

,_id,Año,Especie,Municipio,Número de explotaciones,Número de reses,Reses por explotación
0,6a59134306b825f05193e82d,2001,Vacuno,39001 - Alfoz de Lloredo,170.0,3829.0,22.52
1,6a59134306b825f05193e82e,2001,Vacuno,39002 - Ampuero,128.0,3251.0,25.40
2,6a59134306b825f05193e82f,2001,Vacuno,39003 - Anievas,59.0,1405.0,23.81
3,6a59134306b825f05193e830,2001,Vacuno,39004 - Arenas de Iguña,194.0,3925.0,20.23
4,6a59134306b825f05193e831,2001,Vacuno,39005 - Argoños,15.0,501.0,33.40
...,...,...,...,...,...,...,...
13294,6a59134406b825f05194370c,2022,Caprino,39098 - Villacarriedo,39.0,322.0,8.26
13295,6a59134406b825f05194370d,2022,Caprino,39099 - Villaescusa,67.0,407.0,6.07
13296,6a59134406b825f05194370e,2022,Caprino,39100 - Villafufre,36.0,187.0,5.19
13297,6a59134406b825f05194370f,2022,Caprino,39101 - Valle de Villaverde,15.0,115.0,7.67
13298,6a59134406b825f051943710,2022,Caprino,39102 - Voto,78.0,706.0,9.05

In [ ]:
#5
cattle_soba_ovino = cattle.ganado.find({
    "Especie": "Ovino",
    "Municipio": "39083 - Soba"
})


df_soba_ovino = pd.DataFrame(list(cattle_soba_ovino))

df_soba_ovino

,_id,Año,Especie,Municipio,Número de explotaciones,Número de reses,Reses por explotación
0,6a59134306b825f05193e9b1,2001,Ovino,39083 - Soba,65.0,2412.0,37.11
1,6a59134306b825f05193ea17,2001,Ovino,39083 - Soba,65.0,2412.0,37.11
2,6a59134306b825f05193ea7d,2001,Ovino,39083 - Soba,65.0,2412.0,37.11
3,6a59134306b825f05193ed47,2002,Ovino,39083 - Soba,63.0,2291.0,36.37
4,6a59134306b825f05193edad,2002,Ovino,39083 - Soba,63.0,2291.0,36.37
...,...,...,...,...,...,...,...
61,6a59134406b825f0519431cf,2021,Ovino,39083 - Soba,95.0,1567.0,16.49
62,6a59134406b825f051943235,2021,Ovino,39083 - Soba,95.0,1567.0,16.49
63,6a59134406b825f0519434ff,2022,Ovino,39083 - Soba,96.0,1493.0,15.55
64,6a59134406b825f051943565,2022,Ovino,39083 - Soba,96.0,1493.0,15.55
65,6a59134406b825f0519435cb,2022,Ovino,39083 - Soba,96.0,1493.0,15.55

In [ ]:
#6
import plotly.express as px


fig = px.bar(df_soba_ovino.groupby('Año')['Número de reses'].sum().reset_index(),
             x="Año", y="Número de reses",
             color = "Número de reses",
             title="Número Total de Reses Ovinas por Año en Soba")
fig.show()

In [ ]:
#7
for doc in cattle.ganado.find():
    municipio_full = doc.get('Municipio')
    if municipio_full and ' - ' in municipio_full:
        municipality_code, municipality_name = municipio_full.split(' - ', 1)
        cattle.ganado.update_one(
            {'_id': doc['_id']},
            {
                '$set': {
                    'municipality_code': municipality_code.strip(),
                    'municipality_name': municipality_name.strip()
                },
                '$unset': {'Municipio': ''} # Remove the old field
            }
        )

df = pd.DataFrame(list(cattle.ganado.find()))
df

,_id,Año,Especie,Número de explotaciones,Número de reses,Reses por explotación,municipality_code,municipality_name
0,6a59134306b825f05193e82d,2001,Vacuno,170.0,3829.0,22.52,39001,Alfoz de Lloredo
1,6a59134306b825f05193e82e,2001,Vacuno,128.0,3251.0,25.40,39002,Ampuero
2,6a59134306b825f05193e82f,2001,Vacuno,59.0,1405.0,23.81,39003,Anievas
3,6a59134306b825f05193e830,2001,Vacuno,194.0,3925.0,20.23,39004,Arenas de Iguña
4,6a59134306b825f05193e831,2001,Vacuno,15.0,501.0,33.40,39005,Argoños
...,...,...,...,...,...,...,...,...
20191,6a59134406b825f05194370c,2022,Caprino,39.0,322.0,8.26,39098,Villacarriedo
20192,6a59134406b825f05194370d,2022,Caprino,67.0,407.0,6.07,39099,Villaescusa
20193,6a59134406b825f05194370e,2022,Caprino,36.0,187.0,5.19,39100,Villafufre
20194,6a59134406b825f05194370f,2022,Caprino,15.0,115.0,7.67,39101,Valle de Villaverde
20195,6a59134406b825f051943710,2022,Caprino,78.0,706.0,9.05,39102,Voto

In [ ]:
#8
import json

data = list(cattle.ganado.find({}))

for doc in data:
    doc['_id'] = str(doc['_id'])

with open('cattle_results.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)